### ISSUE TITLE
线上出现Attempt to invoke interface method 'int java.util.List.size()' on a null object reference的崩溃，什么情况下this.getOpenImageBeans()会为null呢？

### ISSUE THREAD

**Issue by BugMonkey** [FlyJingFish/OpenImage#30]
**描述一下大概怎么回事**
线上出现很多这样的崩溃

**如何复现**
暂时没有复现步骤

**错误日志**
	java.lang.RuntimeException: Unable to start activity ComponentInfo{com.camera.zdazz/com.flyjingfish.openimagelib.StandardOpenImageActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3815)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3977)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6013)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5902)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:71)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2374)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8249)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
	at com.flyjingfish.openimagelib.OpenImageActivity.initIndicator(OpenImageActivity.java:31)
	at com.flyjingfish.openimagelib.OpenImageActivity.initStyleConfig(OpenImageActivity.java:39)
	at com.flyjingfish.openimagelib.OpenImageActivity.onCreate(OpenImageActivity.java:7)
	at android.app.Activity.performCreate(Activity.java:8130)
	at android.app.Activity.performCreate(Activity.java:8110)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1343)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3781)
	... 15 more

**截图说明**
![image](https://github.com/FlyJingFish/OpenImage/assets/22151098/cdb14d60-8898-4e84-9de2-527f1d9f4290)

**设备信息:**
 - 手机型号: OPPO PHZ110 	HONOR ANB-AN00 等
 - Android版本 Android 14
 - 使用的哪个库及其版本    "io.github.FlyJingFish.OpenImage:OpenImageFullLib:2.2.1"

**Comment by FlyJingFish** [comment]
这个问题不容易复现，你直接用最新版吧[2.2.2](https://github.com/FlyJingFish/OpenImage/releases/tag/v2.2.2)
