### ISSUE TITLE
 java.lang.NullPointerException: Attempt to read from field 'ux0 qx0.a' on a null object reference

### ISSUE THREAD

**Issue by BugMonkey** [FlyJingFish/OpenImage#31]
**描述一下大概怎么回事**
线上遇到的崩溃

**如何复现**
暂无复现步骤

**错误日志**
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.camera.zdazz/com.flyjingfish.openimagelib.StandardOpenImageActivity}: java.lang.NullPointerException: Attempt to read from field 'ux0 qx0.a' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3720)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3887)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:140)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:100)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2317)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:263)
	at android.app.ActivityThread.main(ActivityThread.java:8292)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
Caused by: java.lang.NullPointerException: Attempt to read from field 'ux0 qx0.a' on a null object reference
	at w5.onCreate(BaseFragment.java:5)
	at com.flyjingfish.openimagelib.BaseImageFragment.onCreate(Unknown Source:0)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:6)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:5)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:21)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:3)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:57)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3)
	at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:4)
	at androidx.fragment.app.FragmentController.dispatchCreate(Unknown Source:4)
	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:3)
	at com.flyjingfish.openimagelib.a.onCreate(BaseActivity.java:1)
	at com.flyjingfish.openimagelib.OpenImageActivity.onCreate(OpenImageActivity.java:8)
	at android.app.Activity.performCreate(Activity.java:8146)
	at android.app.Activity.performCreate(Activity.java:8130)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3689)
	... 11 more

**设备信息:**
 - 手机型号: OPPO PCHM10 、OPPO A73等
 - Android版本   Android  11、7.1.1等
 - OpenImageGlideLib:2.2.2]

**Comment by BugMonkey** [comment]
Thread Name: 'main'
Back traces starts.
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.camera.zdazz/com.camera.zdazz.ui.photos.ImageActivity}: java.lang.NullPointerException: Attempt to read from field 'ux0 qx0.a' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4065)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4252)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6258)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:6149)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2618)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8673)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
Caused by: java.lang.NullPointerException: Attempt to read from field 'ux0 qx0.a' on a null object reference
	at x5.onCreate(BaseFragment.java:5)
	at com.flyjingfish.openimagelib.BaseImageFragment.onCreate(Unknown Source:0)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:6)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:5)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:21)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:3)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:57)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3)
	at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:4)
	at androidx.fragment.app.FragmentController.dispatchCreate(Unknown Source:4)
	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:3)
	at com.flyjingfish.openimagelib.a.onCreate(BaseActivity.java:1)
	at com.flyjingfish.openimagelib.OpenImageActivity.onCreate(OpenImageActivity.java:8)
	at com.camera.zdazz.ui.photos.ImageActivity.onCreate(Native Method)
	at android.app.Activity.performCreate(Activity.java:8214)
	at android.app.Activity.performCreate(Activity.java:8202)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1320)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4038)
	... 13 more
Back traces ends.
