### ISSUE TITLE
加载超宽大图崩溃

### ISSUE THREAD

**Issue by appdev** [FlyJingFish/OpenImage#37]
**描述一下大概怎么回事**
加载手机的全景照片会崩溃,图片大小30m。我测试了一下加载其他30m+的图片不会崩溃，只有加载超宽的会崩溃。
图片比较大，加载不出来可以直接下载：
http://put.run/d6952084-23b2-4e52-b0cf-c20109f6c34b.jpg
![](http://put.run/d6952084-23b2-4e52-b0cf-c20109f6c34b.jpg)
**如何复现**
加载上面的图片必崩

**错误日志**
```java
 java.lang.RuntimeException: Canvas: trying to draw too large(377719680bytes) bitmap.
                                         	at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:266)
                                         	at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:94)
                                         	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:549)
                                         	at android.widget.ImageView.onDraw(ImageView.java:1446)
                                         	at com.flyjingfish.openimagelib.photoview.PhotoView.onDraw(PhotoView.java:415)
                                         	at android.view.View.draw(View.java:24627)
                                         	at android.view.View.updateDisplayListIfDirty(View.java:23493)
                                         	at android.view.View.draw(View.java:24357)
                                         	at android.view.ViewGroup.drawChild(ViewGroup.java:4576)
                                         	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4337)
                                         	at android.view.View.draw(View.java:24630)
                                         	at android.view.View.updateDisplayListIfDirty(View.java:23493)
                                         	at android.view.View.draw(View.java:24357)
                                         	at android.view.ViewGroup.drawChild(ViewGroup.java:4576)
                                         	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4337)
                                         	at android.view.View.draw(View.java:24630)
                                         	at android.view.View.updateDisplayListIfDirty(View.java:23493)
                                         	at android.view.View.draw(View.java:24357)
                                         	at android.view.ViewGroup.drawChild(ViewGroup.java:4576)
                                         	at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:5204)
                                         	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4337)
                                         	at android.view.View.draw(View.java:24630)
                                         	at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4603)
                                         	at android.view.View.updateDisplayListIfDirty(View.java:23493)
                                         	at android.view.View.draw(View.java:24357)
                                         	at android.view.ViewGroup.drawChild(ViewGroup.java:4576)
                                         	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4337)
                                         	at android.view.View.draw(View.java:24630)
                                         	at android.view.View.updateDisplayListIfDirty(View.java:23493)
                                         	at android.view.View.draw(View.java:24357)
                                         	at android.view.ViewGroup.drawChild(ViewGroup.java:4576)
                                         	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4337)
                                         	at android.view.View.draw(View.java:24630)
                                         	at android.view.View.updateDisplayListIfDirty(View.java:23493)
                                         	at android.view.View.draw(View.java:24357)
                                         	at android.view.ViewGroup.drawChild(ViewGroup.java:4576)
                                         	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4337)
                                         	at android.view.View.draw(View.java:24630)
                                         	at android.view.View.updateDisplayListIfDirty(View.java:23493)
                                         	at android.view.View.draw(View.java:24357)
                                         	at android.view.ViewGroup.drawChild(ViewGroup.java:4576)
                                         	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4337)
                                         	at android.view.View.draw(View.java:24630)
                                         	at android.view.View.updateDisplayListIfDirty(View.java:23493)
                                         	at android.view.View.draw(View.java:24357)
                                         	at android.view.ViewGroup.drawChild(ViewGroup.java:4576)
                                         	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4337)
                                         	at android.view.View.draw(View.java:24630)
                                         	at android.view.View.updateDisplayListIfDirty(View.java:23493)
                                         	at android.view.View.draw(View.java:24357)
                                         	at android.view.ViewGroup.drawChild(ViewGroup.java:4576)
                                         	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4337)
                                         	at android.view.View.draw(View.java:24630)
                                         	at android.view.View.updateDisplayListIfDirty(View.java:23493)
                                         	at android.view.View.draw(View.java:24357)
                                         	at android.view.ViewGroup.drawChild(ViewGroup.java:4576)
                                         	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4337)
                                         	at android.view.View.draw(View.java:24630)
                                         	at android.view.View.updateDisplayListIfDirty(View.java:23493)
                                         	at android.view.View.draw(View.java:24357)
                                         	at android.view.ViewGroup.drawChild(ViewGroup.java:4576)
                                         	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4337)
                                         	at android.view.View.draw(View.java:24630)
                                         	at com.android.internal.policy.DecorView.draw(DecorView.java:827)
                                         	at android.view.View.updateDisplayListIfDirty(View.java:23493)
                                         	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:694)
                                         	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:700)
                                         	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:798)
10:46:36.426 CrashReport              E  	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5313)
                                         	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4975)
                                         	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4093)
                                         	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2718)
                                         	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9937)
                                         	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1406)
                                         	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1415)
                                         	at android.view.Choreographer.doCallbacks(Choreographer.java:1015)
                                         	at android.view.Choreographer.doFrame(Choreographer.java:945)
                                         	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1389)
                                         	at android.os.Handler.handleCallback(Handler.java:959)
                                         	at android.os.Handler.dispatchMessage(Handler.java:100)
                                         	at android.os.Looper.loopOnce(Looper.java:232)
                                         	at android.os.Looper.loop(Looper.java:317)
```

**截图说明**

**设备信息:**
 - 手机型号: pixel 7a
 - Android版本: android 14
 - 使用的哪个库及其版本：最新版本

**Comment by FlyJingFish** [comment]
最新版已修复
